Repository appliedepi/epiRhandbook_jp, pull requests merged in 2022-07, with the labels that each got.

#9 05 packages suggested mf 20210923
  new_pages/packages_suggested.Rmd
Labels: ready-to-be-merged

#57 01 editorial style ss 20220528
  new_pages/editorial_style.Rmd
Labels: arranging-with-other-chapters

#58 02 data used ss 20220528
  new_pages/data_used.Rmd
Labels: ready-to-be-merged

#56 04 transition to r yn 20210923
  new_pages/transition_to_R.Rmd
Labels: ready-to-be-merged

#32 07 importing mf 20210923
  new_pages/importing.Rmd
Labels: ready-to-be-merged

#22 08 cleaning tt 20210923
  new_pages/cleaning.Rmd
Labels: ready-to-be-merged

#17 10 characters strings ya 20210923
  new_pages/characters_strings.Rmd
Labels: ready-to-be-merged

#60 06 r projects yn 20220605
  new_pages/r_projects.Rmd
Labels: ready-to-be-merged

#63 09 dates tn 20220716
  new_pages/dates.Rmd
Labels: ready-to-be-merged

#38 11 facotr mf 20210923
  new_pages/factors.Rmd
Labels: ready-to-be-merged

#59 12 pivoting ykw 20220528
  new_pages/pivoting.Rmd
Labels: ready-to-be-merged

#64 13 grouping yy 20220716
  new_pages/grouping.Rmd
Labels: ready-to-be-merged

#37 14 joining matching mf 20210923
  new_pages/joining_matching.Rmd
Labels: ready-to-be-merged

#13 15 deduplication tn 20210923
  new_pages/deduplication.Rmd
Labels: ready-to-be-merged

#65 16 iteration yky 20220716
  new_pages/iteration.Rmd
Labels: ready-to-be-merged

#61 32 epicurves ykk 20220619
  new_pages/epicurves.Rmd
Labels: ready-to-be-merged

#42 34 heatmaps ykk 20210923
  new_pages/heatmaps.Rmd
Labels: ready-to-be-merged

#46 35 diagrams yb 20210923
  new_pages/diagrams.Rmd
Labels: ready-to-be-merged

#52 40 rmarkdown_af_20210923
  new_pages/rmarkdown.Rmd
Labels: ready-to-be-merged

#48 25 contact tracing hk 20210923
  new_pages/contact_tracing.Rmd
Labels: ready-to-be-merged

#54 42 flexdashboard nn 20210923 Initial pull request
  new_pages/flexdashboard.Rmd
Labels: organizing

#67 delete DS_Store
  .DS_Store
Labels: organizing

#66 28 gis yb 20210923
  new_pages/gis.Rmd
Labels: review-started

#18 03_basics_ys_20210923 Update translation
  new_pages/basics.Rmd
Labels: review-ended

#6 41_reportfactory_nn_20210923
  new_pages/reportfactory.Rmd
Labels: organizing

#8 38 phylogenetic trees rf 20210923
  new_pages/phylogenetic_trees.Rmd
Labels: organizing

#20 47 errors yb 20210923
  new_pages/errors.Rmd
Labels: organizing

#24 39 interactive plots yi 20210923
  new_pages/interactive_plots.Rmd
Labels: organizing

#25 43 shiny basics nn 20210923
  new_pages/shiny_basics.Rmd
Labels: organizing

#27 44 writing functions yh 20210923
  new_pages/writing_functions.Rmd
Labels: organizing

#28 46 collaboration yb 20210923
  new_pages/collaboration.Rmd
Labels: organizing

#30 37 transmission chains yb 20210923
  new_pages/transmission_chains.Rmd
Labels: organizing

#34 45 directories yh 20210923
  new_pages/directories.Rmd
Labels: organizing

#39 50 data table mf 20210923
  new_pages/data_table.Rmd
Labels: organizing

#44 48 help hk 20210923
  new_pages/help.Rmd
Labels: organizing

#49 36 combination analysis hk 20210923
  new_pages/combination_analysis.Rmd
Labels: organizing

#50 49 network drives hk 20210923
  new_pages/network_drives.Rmd
Labels: organizing

#62 33 age pyramid ykw 20210923
  new_pages/age_pyramid.Rmd
Labels: organizing
