Repository appliedepi/epiRhandbook_jp, pull requests merged in 2022-08, with the labels that each got.

#72 28 gis yb 20210923
  new_pages/gis.Rmd
Labels: review-required

#74 delete an origin file
  new_pages/survival_analysis_original.Rmd
Labels: organizing

#75 00 category files
  new_pages/cat_about_book.Rmd
  new_pages/cat_advanced.Rmd
  new_pages/cat_analysis.Rmd
  new_pages/cat_basics.Rmd
  new_pages/cat_data_management.Rmd
  new_pages/cat_data_viz.Rmd
  new_pages/cat_introduction.Rmd
  new_pages/cat_misc.Rmd
  new_pages/cat_preview.Rmd
  new_pages/cat_reports_dashboards.Rmd
Labels: organizing

#76 Update pivoting.Rmd
  new_pages/pivoting.Rmd
Labels: organizing

#70 19 regression ss 20220721
  new_pages/regression.Rmd
Labels: ready-to-be-merged

#71 26 survey analysis af 20220721
  new_pages/survey_analysis.Rmd
Labels: ready-to-be-merged

#73 bookdown compile ready
  new_pages/data_used.Rmd
  new_pages/epicurves.Rmd
  new_pages/heatmaps.Rmd
  new_pages/interactive_plots.Rmd
  new_pages/missing_data.Rmd
  new_pages/pivoting.Rmd
  new_pages/time_series.Rmd
Labels: organizing
